Change joinSpace to use linked wallets again UserEntitlements, and to fetch root key for wallet
river-build/river pull request #108
Opened 2024-06-04 20:58 UTC by clemire

2 changes here:
1. membership facet now fetches linked wallets and uses them to evaluate user entitlements for joining the space
2. Entitled.sol wallet linking code is modified to fetch the root key for a user if that user itself does not have any wallets attached to it, and return that set of wallets instead.

2024-06-04 22:38 UTC, giuseppecrj requested changes

2024-06-04 22:38 UTC, giuseppecrj commented on contracts/test/spaces/membership/MembershipBaseSetup.sol
> +    assert(membership.balanceOf(alice) == 1);
`assertEq`

2024-06-04 22:38 UTC, giuseppecrj commented on contracts/test/spaces/membership/unit/MembershipJoinSpace.t.sol
> +      IWalletLinkBase.LinkedWallet(emilyWallet.addr, signature),
import IWalletLinkBase into test contract to avoid using IWalletLinkBase.LinkedWallet

2024-06-05 00:04 UTC, brianathere approved these changes

2024-06-06 20:48 UTC, giuseppecrj commented
Testnet Proposal: https://testnets.llama.xyz/orgs/river/base-sepolia/actions/102

2024-06-06 21:03 UTC, giuseppecrj approved these changes

2024-06-06 21:22 UTC, texuf commented on packages/generated/deployments/gamma/base/addresses/space.json
> -{"address":"0x0Fd3f9E6C2530424b8C82dcFf3552e91c965DC1f"}
@clemire did you deploy to gamma?

2024-06-06 23:40 UTC, merged

2024-06-06 23:42 UTC, clemire commented on packages/generated/deployments/gamma/base/addresses/space.json
> -{"address":"0x0Fd3f9E6C2530424b8C82dcFf3552e91c965DC1f"}
doing right now!