Update entitlement gated to finalize all roleids before clearing transaction
river-build/river pull request #1126
Opened 2024-09-20 18:42 UTC by giuseppecrj

This update enhances the entitlement check result handling in the EntitlementGatedBase contract:

**Result Posting and Event Emission:**
* Now occurs when the final status is PASSED OR when all role IDs have completed their checks.
* This ensures that results are posted and events are emitted for both successful checks and when all checks are complete, regardless of the outcome.

**Transaction Removal:**
* The transaction is now removed only when all role IDs have completed their checks.
* This change ensures that all necessary data is retained until the entire process is complete, improving data consistency and allowing for potential auditing or review of partial results.

These modifications provide a more comprehensive and flexible approach to handling entitlement check results, especially in scenarios involving multiple roles or complex permission structures.

2024-09-20 19:20 UTC, clemire requested changes

2024-09-23 16:31 UTC, giuseppecrj commented on contracts/src/spaces/facets/gated/EntitlementGatedBase.sol
test cases added in the latest push.

2024-09-23 16:31 UTC, giuseppecrj commented on contracts/src/spaces/facets/gated/EntitlementGatedBase.sol
> +      if (finalStatus == NodeVoteStatus.PASSED || allRoleIdsCompleted) {
fixed in latest push.

2024-09-23 16:58 UTC, giuseppecrj commented
Addresses on #1138

2024-09-23 18:03 UTC, clemire commented on contracts/src/spaces/facets/gated/EntitlementGatedBase.sol
> +      if (finalStatusForRole == NodeVoteStatus.PASSED || allRoleIdsCompleted) {
nice

2024-09-23 18:04 UTC, clemire commented on contracts/test/crosschain/EntitlementGated.t.sol
> +    // second roleId is entitled
nit - I think this comment is wrong, second role is also not entitled.

2024-09-23 20:05 UTC, shuhuiluo approved these changes

2024-09-23 21:49 UTC, giuseppecrj commented on contracts/src/spaces/facets/gated/EntitlementGatedBase.sol
> +      NodeVote storage tempVote = nodeVotesForRole[i];
will update in another PR

2024-09-23 21:50 UTC, merged