feat(contract): points for membership fee
river-build/river pull request #1548
Opened 2024-11-18 09:51 UTC by shuhuiluo

Introduce the `RiverPoints` contract implementing the ERC20 standard with metadata using associated storage, balance, and allowance management libraries. These changes establish the foundational structure for handling `RiverPoints` tokens securely and efficiently.

Replaced `river` with `spaceFactory` in `RiverPoints` to support space-based minting. Added new functionality in `MembershipJoin` to charge join fees, handle partner and referral fees, and credit points accordingly. Enhanced security and modularity by introducing the `onlySpace` modifier and custom error handling.

2024-11-18 16:02 UTC, giuseppecrj commented
Why are we using a custom ERC20 implementation instead of a standard?

2024-11-18 17:09 UTC, shuhuiluo commented on contracts/src/spaces/facets/membership/join/MembershipJoin.sol
> +    }
It will fail existing tests if checking for success.

2024-11-18 17:13 UTC, shuhuiluo commented
> Why are we using a custom ERC20 implementation instead of a standard?

Because there's no `ERC20Facet` and `ERC20Upgradeable` is an overkill.

2024-11-18 18:36 UTC, giuseppecrj commented on contracts/src/spaces/facets/membership/join/MembershipJoin.sol
> +    }
update tests then.

2024-11-18 18:37 UTC, giuseppecrj commented on contracts/src/spaces/facets/membership/join/MembershipJoin.sol
> +    uint256 payment = _getCapturedValue(transactionId);
Move renaming to separate PR

2024-11-18 19:24 UTC, shuhuiluo commented on contracts/src/spaces/facets/membership/join/MembershipJoin.sol
> +    }
I don't think failure to mint points should block membership minting.

2024-11-18 19:27 UTC, shuhuiluo commented
> Why are we using a custom ERC20 implementation instead of a standard?

@giuseppecrj Making an `ERC20Facet` is also an overkill. I don't want to inherit `ERC20Facet` and override every function.

`ERC20Lib` is a rewrite of OpenZeppelin `ERC20Upgradeable`, courtesy of [solitude](https://github.com/shuhuiluo/solitude).

2024-11-18 19:28 UTC, shuhuiluo commented on contracts/src/spaces/facets/membership/join/MembershipJoin.sol
> +    uint256 payment = _getCapturedValue(transactionId);
Yes sir.

2024-11-18 19:48 UTC, giuseppecrj commented
> `20Facet` and override every function.

Create ERC20Base for this, same as ERC721ABase.sol

2024-11-18 19:49 UTC, shuhuiluo commented
> > `20Facet` and override every function.
> 
> Create ERC20Base for this, same as ERC721ABase.sol

`ERC20Base` will just be a wrapper of `ERC20Lib`.

2024-11-18 19:51 UTC, giuseppecrj commented on contracts/src/spaces/facets/membership/join/MembershipJoin.sol
> +    }
I disagree, please update appropiately.

2024-11-18 21:51 UTC, giuseppecrj requested changes

2024-11-18 21:51 UTC, giuseppecrj commented on contracts/src/primitive/AllowanceMap.sol
> +using AllowanceLib for AllowanceMap global;
can we avoid using global and instead declare it in the RiverPoints contract directly? If we have different versions of AllowanceLib in different facets, can this cause conflicts?

It makes the dependencies more explicit, which is crucial for diamond proxy patterns.

2024-11-20 17:52 UTC, pfives approved these changes

2024-11-21 01:07 UTC, merged