update deployment to allow for 4337
river-build/river pull request #169
Opened 2024-06-12 23:23 UTC by giuseppecrj

2024-06-13 06:25 UTC, pfives commented on contracts/test/utils/TestUtils.sol
> +      block.chainid == 1337 || block.chainid == 31337 || block.chainid == 31338;
would be nice to have these as constants so we know which actual chains you're looking for here

2024-06-13 15:49 UTC, salzbrenner commented
@giuseppecrj so what should i be doing? Run the stackup repo and then run deploy-contracts.sh? Cos I did that and it still has anvil specific commands that throw errors i.e. `automine`

2024-06-13 20:39 UTC, texuf requested changes
these chain id changes look wrong.
when we launch anvil, we tell it what chain id will be.

2024-06-13 21:52 UTC, salzbrenner commented
i've been trying to get the devnet working outside of river/harmony w/ https://github.com/stackup-wallet/erc-4337-examples
- can spin up devnet fine
- get errors w/ the examples. i reached out to stackup team for guidance

2024-06-14 03:22 UTC, texuf approved these changes
If we run our base chain as a geth chain and or river chain as an anvil chain, I guess this will work, but I still think we should just set the geth chain id to the existing one, otherwise it breaks a lot of other code

2024-06-14 15:29 UTC, giuseppecrj commented
> If we run our base chain as a geth chain and or river chain as an anvil chain, I guess this will work, but I still think we should just set the geth chain id to the existing one, otherwise it breaks a lot of other code

The stackup docker file is confusing, I updated the chain id but it would still default to their 1337

2024-06-14 15:33 UTC, brianathere commented
> > @giuseppecrj so what should i be doing? Run the stackup repo and then run deploy-contracts.sh? Cos I did that and it still has anvil specific commands that throw errors i.e. `automine`
> 
> Yeah, the automine call doesn't exist on anvil, I also had to deploy our contracts one by one

Blocks should be produced on every transaction while in dev mode.

https://geth.ethereum.org/docs/developers/dapp-developer/dev-mode

2024-06-14 20:51 UTC, salzbrenner commented
> If we run our base chain as a geth chain and or river chain as an anvil chain, I guess this will work, but I still think we should just set the geth chain id to the existing one, otherwise it breaks a lot of other code

I tried doing this too w/out success. You can set the --networkId to whatever, but that doesn't set the chain id. To modifiy the chain id, you have to init geth with a genesis block json configuration. And I simply could not figure out how to both init with a genesis config AND run geth in dev mode. Searching online I could not conclude that this was possible or not.

2024-06-14 22:49 UTC, texuf commented
> > If we run our base chain as a geth chain and or river chain as an anvil chain, I guess this will work, but I still think we should just set the geth chain id to the existing one, otherwise it breaks a lot of other code
> 
> I tried doing this too w/out success. You can set the --networkId to whatever, but that doesn't set the chain id. To modifiy the chain id, you have to init geth with a genesis block json configuration. And I simply could not figure out how to both init with a genesis config AND run geth in dev mode. Searching online I could not conclude that this was possible or not.

We will just need to be sure that when we write the deployment files to generaged/deployments/<local_single|local_multi|...etc> that it writes the right chain id - it might just work

2024-06-28 03:06 UTC, closed without merging