Update Platform Requirements with new minimum price getter
river-build/river pull request #178
Opened 2024-06-14 20:52 UTC by giuseppecrj

Testnet Proposals:

* [Upgrade PlatformRequirements Facet on Space Factory](https://testnets.llama.xyz/orgs/river/base-sepolia/actions/117)
* [Upgrade Architect Facet on Space Factory](https://testnets.llama.xyz/orgs/river/base-sepolia/actions/119)
* [Upgrade MembershipFacet on Space](https://testnets.llama.xyz/orgs/river/base-sepolia/actions/118)

2024-06-17 18:10 UTC, salzbrenner approved these changes

2024-06-17 23:05 UTC, clemire reviewed
It may make sense to move the entitlement checker updates into a separate PR since they are unrelated to other changes here

2024-06-18 12:00 UTC, bas-vk requested changes
Don't think you want to add **[core/xchain/server/__debug_bin3947307799](https://github.com/river-build/river/pull/178/files#diff-f2b212f9a751baec74a8dfef0f227a5c6a18a85ab754afa68ca14b4071146dc0)**?

2024-06-18 17:26 UTC, bas-vk approved these changes

2024-06-18 20:44 UTC, merged