Update batch delegation to run by half
river-build/river pull request #1874
Opened 2024-12-18 22:59 UTC by pfives

2024-12-18 23:09 UTC, shuhuiluo requested changes

2024-12-18 23:09 UTC, shuhuiluo commented on contracts/src/tokens/river/mainnet/delegation/ProxyBatchDelegation.sol
>      address[] memory delegators = rvr.getDelegators();
Should create a new array because all four arrays have to align.

2024-12-18 23:18 UTC, shuhuiluo approved these changes

2024-12-18 23:21 UTC, jterzis approved these changes

2024-12-19 01:40 UTC, giuseppecrj commented
tests failing

2024-12-19 19:41 UTC, pfives commented
lgtm

2024-12-19 21:00 UTC, merged