alpha tipping updates
river-build/river pull request #1927
Opened 2024-12-30 19:42 UTC by giuseppecrj

2024-12-30 20:07 UTC, shuhuiluo requested changes

2024-12-30 20:07 UTC, shuhuiluo commented on contracts/scripts/interactions/InteractDiamondCut.s.sol
This is hand-wavy. Can we make the script parameterizable?

2024-12-31 15:41 UTC, giuseppecrj commented on contracts/scripts/interactions/InteractDiamondCut.s.sol
no.

2024-12-31 17:56 UTC, shuhuiluo approved these changes

2025-01-03 15:54 UTC, closed without merging