feat(contract): mainnet delegation relayer
river-build/river pull request #1932
Opened 2024-12-31 00:23 UTC by shuhuiluo

2025-01-01 00:01 UTC, giuseppecrj commented
Not seeing any tests.

2025-01-01 00:01 UTC, giuseppecrj requested changes
tests

2025-01-06 16:36 UTC, giuseppecrj approved these changes

2025-01-06 16:36 UTC, giuseppecrj commented on contracts/scripts/deployments/facets/DeployMainnetDelegation.s.sol
>      addSelector(MainnetDelegation.setProxyDelegation.selector);
Do we still need all these functions?

2025-01-06 16:36 UTC, giuseppecrj commented on contracts/src/tokens/river/base/delegation/IMainnetDelegation.sol
> +  /// @param encodedMsgs The encoded delegation messages
who calls this function? provide some context

2025-01-06 16:36 UTC, giuseppecrj commented on contracts/src/tokens/river/base/delegation/MainnetDelegation.sol
> +  /*´:°•.°+.*•´.*:˚.°*.˚•´.°:°•.°•.*•´.*:˚.°*.˚•´.°:°•.°+.*•´.*:*/
✨✨✨✨✨

2025-01-06 16:36 UTC, giuseppecrj commented on contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol
> +      mstore(0x40, delegation)
nice!

2025-01-06 16:36 UTC, shuhuiluo commented on contracts/src/tokens/river/base/delegation/IMainnetDelegation.sol
> +  /// @param encodedMsgs The encoded delegation messages
The owner.

2025-01-06 16:36 UTC, shuhuiluo commented on contracts/scripts/deployments/facets/DeployMainnetDelegation.s.sol
>      addSelector(MainnetDelegation.setProxyDelegation.selector);
No. Another PR.

2025-01-06 16:36 UTC, shuhuiluo commented on contracts/src/tokens/river/base/delegation/MainnetDelegation.sol
> +  /*´:°•.°+.*•´.*:˚.°*.˚•´.°:°•.°•.*•´.*:˚.°*.˚•´.°:°•.°+.*•´.*:*/
Solady convention.

2025-01-06 16:51 UTC, jterzis commented on contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol
> +    for (uint256 i; i < delegators.length; ++i) {
Are there any checks we can perform on the encodedMsgs passed into relayDelegations to prevent the undesired side effect that we erase delegations that were not actually stale ? In general, I'd prefer explicitly passing in the set of new and old delegations with a flag to unset stale ones. The way this currently is implemented, there's a risk of setting stale delegations that are not in fact stale just by calling the function with incorrect input.

2025-01-06 19:06 UTC, shuhuiluo commented on contracts/src/tokens/river/base/delegation/MainnetDelegationBase.sol
> +    for (uint256 i; i < delegators.length; ++i) {
We verify the message against the bridged digest. So the decoded inputs are current mainnet delegations. The function can only be called by governance.

2025-01-06 20:21 UTC, jterzis approved these changes

2025-01-06 21:58 UTC, merged