Add circuit breakers to oracle pricing
river-build/river pull request #221
Opened 2024-06-20 04:13 UTC by giuseppecrj

2024-06-20 06:05 UTC, texuf approved these changes

2024-06-20 17:35 UTC, clemire requested changes

2024-06-20 17:35 UTC, clemire commented on contracts/src/spaces/facets/membership/pricing/tiered/TieredLogPricingOracle.sol
> +    if (updatedAt == 0) revert TieredLogPricingOracle__InvalidRound();
`TieredLogPricingOracle__InvalidTimestamp`?

2024-06-20 19:51 UTC, bas-vk approved these changes

2024-06-21 21:57 UTC, clemire approved these changes

2024-06-25 01:44 UTC, merged