add modifier to EntitlementChecker to only allow registered operator to be checkers
river-build/river pull request #80
Opened 2024-05-28 16:30 UTC by giuseppecrj

2024-05-31 21:36 UTC, brianathere approved these changes

2024-05-31 21:46 UTC, clemire commented on contracts/test/base/registry/NodeOperator.t.sol
> +  //   nodenodeOperator.addSpaceDelegation(address(0), randomOperator);
accidental changes?

2024-05-31 22:51 UTC, clemire requested changes
At a v high level, this looks fine to me - but I don't know what's going on in a lot of / most of this PR, so I'm not sure I'm the best person to approve it. If you can't get someone else, let me know if you want to jump on a call.

2024-06-03 15:20 UTC, giuseppecrj commented
> At a v high level, this looks fine to me - but I don't know what's going on in a lot of / most of this PR, so I'm not sure I'm the best person to approve it. If you can't get someone else, let me know if you want to jump on a call.
> 
> request for changes for a nit.

@clemire The main component that's either missing or I'm not able to asses is whether or not we're registering operators prior to calling `registerNode` on the entitlement checker contract. If not, any calls to registerNode will fail on tests.

cc. @brianathere

2024-06-03 22:41 UTC, brianathere approved these changes

2024-06-04 16:48 UTC, clemire commented on core/xchain/create_multi.sh
> +source ../../contracts/.env.localhost
@brianathere I made the following changes to get xchain to properly register itself on startup, to mimic how stream node registers when the service is being launched (using the same wallet as the operator address), but was unsuccessful.

2024-06-04 16:48 UTC, clemire commented on core/xchain/create_multi.sh
> +source ../../contracts/.env.localhost
Right now xchain isn't launching, and it's failing on the registration step. This is why the skd tests for space admission that require xchain in the loop are failing.

2024-06-05 15:03 UTC, texuf commented on core/xchain/launch_multi.sh
> +OPERATOR_ADDRESS=$(cast wallet addr $LOCAL_PRIVATE_KEY)
you can't hard code `local_single` here - you need to rewpect the RUN_ENV

2024-06-05 15:05 UTC, texuf requested changes
i can look through this in more detail after 9:00

2024-06-05 16:14 UTC, texuf commented on core/xchain/launch_multi.sh
> +OPERATOR_ADDRESS=$(cast wallet addr $LOCAL_PRIVATE_KEY)
just change this to 
```
BASE_REGISTRY_ADDRESS=$(jq -r '.address' ../../packages/generated/deployments/${RIVER_ENV}/base/addresses/baseRegistry.json)
```

but it doesn't seem to fix it

2024-06-05 16:28 UTC, texuf commented
> I have added 2 steps that first register a node operator and that operator than registeres the xchain nodes. Not sure if this is the best place for it because running the script a second time will now give an error because it tries to register an operator/node for the second time. For CI that isn't an issue, for development it can be annoying.

yes, can you move these calls to the create_multi.sh script and fix the hard coded local_single (change to ${RIVER_ENV})?

2024-06-05 16:32 UTC, texuf commented
> > I have added 2 steps that first register a node operator and that operator than registeres the xchain nodes. Not sure if this is the best place for it because running the script a second time will now give an error because it tries to register an operator/node for the second time. For CI that isn't an issue, for development it can be annoying.
> 
> yes, can you move these calls to the create_multi.sh script and fix the hard coded local_single (change to ${RIVER_ENV})?

Actually there are several things that need to happen for this to work, i will update this pr

2024-06-05 18:35 UTC, texuf approved these changes

2024-06-05 21:10 UTC, merged